[project]
name = "websearch-agent"
version = "0.1.0"
description = "A deep search agent using Tavily and local context."
dependencies = [
    "tavily-python>=0.1.1",
    "python-dotenv",
    "google-generativeai>=0.7.0",
    "requests>=2.31.0"
]
requires-python = ">=3.9"


python = "python"